import type { MergedSubscriptionResponse } from '@/app/api/subscriptions/route'
import type { UserSubscriptionWithDetails, CurrencyCode } from '@/lib/types/database'

export type DemoSubscriptionWithDetails = UserSubscriptionWithDetails & {
  category?: string
}

export type DemoMergedSubscription = Omit<MergedSubscriptionResponse, 'subscriptions'> & {
  category?: string
  subscriptions: DemoSubscriptionWithDetails[]
}

const today = new Date()
const daysFromNow = (days: number) => {
  const date = new Date(today)
  date.setDate(date.getDate() + days)
  return date.toISOString().split('T')[0]
}
const daysAgo = (days: number) => daysFromNow(-days)
const yearsAgo = (years: number, monthOffset = 0) => {
  const date = new Date(today)
  date.setFullYear(date.getFullYear() - years)
  date.setMonth(date.getMonth() + monthOffset)
  return date.toISOString().split('T')[0]
}

function createSubscription(
  id: number,
  name: string,
  url: string,
  price: number,
  currency: CurrencyCode,
  startDate: string,
  endDate: string,
  autoRenew: boolean,
  category: string,
  paymentMethod: string,
  unsubscribeUrl: string | null = null,
): DemoSubscriptionWithDetails {
  return {
    id,
    user_id: 'demo-user',
    subscription_service_id: id,
    price,
    currency,
    start_date: startDate,
    end_date: endDate,
    auto_renew: autoRenew,
    payment_method: paymentMethod,
    source_email: null,
    category,
    created_at: startDate,
    subscription_service: {
      name,
      url,
      unsubscribe_url: unsubscribeUrl,
    },
  }
}

export const SAMPLE_SUBSCRIPTIONS: DemoMergedSubscription[] = [
  {
    name: 'Netflix',
    serviceUrl: 'https://netflix.com',
    price: 15.99,
    currency: 'USD',
    startDate: daysAgo(180),
    endDate: daysFromNow(185),
    autoRenew: true,
    active: true,
    category: 'Entertainment',
    spentThisYear: 95.94,
    forecastThisYear: 191.88,
    totalSpent: 95.94,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        1,
        'Netflix',
        'https://netflix.com',
        15.99,
        'USD',
        daysAgo(180),
        daysFromNow(185),
        true,
        'Entertainment',
        'Credit Card',
        'https://www.netflix.com/cancelplan',
      ),
    ],
  },
  {
    name: 'Spotify',
    serviceUrl: 'https://spotify.com',
    price: 10.99,
    currency: 'USD',
    startDate: daysAgo(365),
    endDate: daysFromNow(3), // Renewing soon - will show in upcoming renewals
    autoRenew: true,
    active: true,
    category: 'Entertainment',
    spentThisYear: 131.88,
    forecastThisYear: 131.88,
    totalSpent: 131.88,
    paymentMethod: 'PayPal',
    subscriptions: [
      createSubscription(
        2,
        'Spotify',
        'https://spotify.com',
        10.99,
        'USD',
        daysAgo(365),
        daysFromNow(3),
        true,
        'Entertainment',
        'PayPal',
        'https://www.spotify.com/account/subscription/',
      ),
    ],
  },
  {
    name: 'Adobe Creative Cloud',
    serviceUrl: 'https://adobe.com',
    price: 54.99,
    currency: 'USD',
    startDate: daysAgo(90),
    endDate: daysFromNow(275),
    autoRenew: true,
    active: true,
    category: 'Software',
    spentThisYear: 164.97,
    forecastThisYear: 659.88,
    totalSpent: 164.97,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        3,
        'Adobe Creative Cloud',
        'https://adobe.com',
        54.99,
        'USD',
        daysAgo(90),
        daysFromNow(275),
        true,
        'Software',
        'Credit Card',
        'https://account.adobe.com/plans',
      ),
    ],
  },
  {
    name: 'GitHub Pro',
    serviceUrl: 'https://github.com',
    price: 4.0,
    currency: 'USD',
    startDate: daysAgo(300),
    endDate: daysFromNow(5), // Expiring soon!
    autoRenew: false,
    active: true,
    category: 'Software',
    spentThisYear: 12.0,
    forecastThisYear: 12.0,
    totalSpent: 40.0,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        4,
        'GitHub Pro',
        'https://github.com',
        4.0,
        'USD',
        daysAgo(300),
        daysFromNow(5),
        false,
        'Software',
        'Credit Card',
        'https://github.com/settings/billing',
      ),
    ],
  },
  {
    name: 'Amazon Prime',
    serviceUrl: 'https://amazon.com',
    price: 14.99,
    currency: 'USD',
    startDate: daysAgo(200),
    endDate: daysFromNow(165),
    autoRenew: true,
    active: true,
    category: 'Other',
    spentThisYear: 89.94,
    forecastThisYear: 179.88,
    totalSpent: 89.94,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        5,
        'Amazon Prime',
        'https://amazon.com',
        14.99,
        'USD',
        daysAgo(200),
        daysFromNow(165),
        true,
        'Other',
        'Credit Card',
        'https://www.amazon.com/mc/pipeline',
      ),
    ],
  },
  {
    name: 'Disney+',
    serviceUrl: 'https://disneyplus.com',
    price: 7.99,
    currency: 'USD',
    startDate: daysAgo(400),
    endDate: daysAgo(35),
    autoRenew: false,
    active: false,
    category: 'Entertainment',
    spentThisYear: 23.97,
    forecastThisYear: 23.97,
    totalSpent: 95.88,
    paymentMethod: 'PayPal',
    subscriptions: [
      createSubscription(
        6,
        'Disney+',
        'https://disneyplus.com',
        7.99,
        'USD',
        daysAgo(400),
        daysAgo(35),
        false,
        'Entertainment',
        'PayPal',
        'https://www.disneyplus.com/account/subscription',
      ),
    ],
  },
  {
    name: 'Notion',
    serviceUrl: 'https://notion.so',
    price: 8.0,
    currency: 'USD',
    startDate: yearsAgo(3),
    endDate: yearsAgo(1, 2),
    autoRenew: false,
    active: false,
    category: 'Productivity',
    spentThisYear: 0,
    forecastThisYear: 0,
    totalSpent: 240.0,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        7,
        'Notion',
        'https://notion.so',
        8.0,
        'USD',
        yearsAgo(3),
        yearsAgo(1, 2),
        false,
        'Productivity',
        'Credit Card',
        'https://www.notion.so/profile/billing',
      ),
    ],
  },
  {
    name: 'Dropbox Plus',
    serviceUrl: 'https://dropbox.com',
    price: 9.99,
    currency: 'USD',
    startDate: yearsAgo(2, -3),
    endDate: yearsAgo(1),
    autoRenew: false,
    active: false,
    category: 'Storage',
    spentThisYear: 0,
    forecastThisYear: 0,
    totalSpent: 119.88,
    paymentMethod: 'PayPal',
    subscriptions: [
      createSubscription(
        8,
        'Dropbox Plus',
        'https://dropbox.com',
        9.99,
        'USD',
        yearsAgo(2, -3),
        yearsAgo(1),
        false,
        'Storage',
        'PayPal',
        'https://www.dropbox.com/account/plan',
      ),
    ],
  },
  {
    name: 'YouTube Premium',
    serviceUrl: 'https://youtube.com',
    price: 13.99,
    currency: 'USD',
    startDate: yearsAgo(2),
    endDate: daysFromNow(20),
    autoRenew: true,
    active: true,
    category: 'Entertainment',
    spentThisYear: 41.97,
    forecastThisYear: 167.88,
    totalSpent: 335.76,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        9,
        'YouTube Premium',
        'https://youtube.com',
        13.99,
        'USD',
        yearsAgo(2),
        daysFromNow(20),
        true,
        'Entertainment',
        'Credit Card',
        'https://www.youtube.com/paid_memberships',
      ),
    ],
  },
  {
    name: 'Figma',
    serviceUrl: 'https://figma.com',
    price: 15.0,
    currency: 'USD',
    startDate: yearsAgo(3, 1),
    endDate: yearsAgo(2, 1),
    autoRenew: false,
    active: false,
    category: 'Design',
    spentThisYear: 0,
    forecastThisYear: 0,
    totalSpent: 180.0,
    paymentMethod: 'Credit Card',
    subscriptions: [
      createSubscription(
        10,
        'Figma',
        'https://figma.com',
        15.0,
        'USD',
        yearsAgo(3, 1),
        yearsAgo(2, 1),
        false,
        'Design',
        'Credit Card',
        'https://www.figma.com/billing',
      ),
    ],
  },
]
